###### SPECIAL CASES ######

default_710_min_0.12:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.12
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_min_0.12:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.12
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_min_0.13:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.13
    solver:
      options: gurobi-numeric-focus
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

min_0.03:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.03
    solver:
      options: gurobi-numeric-focus

###### carbon cost ######

min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025

min_0.05:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
    solver:
      options: gurobi-numeric-focus

min_0.1:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1

min_0.15:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15

max_0.025:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025

max_0.05:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05

max_0.1:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1

max_0.15:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15

optimal:
  solving:
    mga:
      enable: false

###### 710 carbon costs ######

710_min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
    solver:
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.05:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.1:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.15:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.025:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.05:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.1:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.15:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15
  sector:
    co2_sequestration_potential:
      2050: 710

710_optimal:
  solving:
    mga:
      enable: false
  sector:
    co2_sequestration_potential:
      2050: 710

###### default ######

default_min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_min_0.05:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_min_0.1:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_min_0.15:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15
    solver:
      options: gurobi-numeric-focus
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_max_0.025:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_max_0.05:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_max_0.1:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_max_0.15:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

default_optimal:
  solving:
    mga:
      enable: false
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0

###### 710 default ######

default_710_min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_min_0.05:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_min_0.1:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_min_0.15:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_max_0.025:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_max_0.05:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_max_0.1:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_max_0.15:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710

default_710_optimal:
  solving:
    mga:
      enable: false
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    solid_biomass_import:
      upstream_emissions_factor: 0
    co2_sequestration_potential:
      2050: 710
