# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

##### TODO adding 0.025 scenarios ######

###### carbon cost ######

# optimal:
#   solving:
#     mga:
#       enable: false
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025

