# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

##### TODO adding 0.025 scenarios ######

###### carbon cost ######

# optimal:
#   solving:
#     mga:
#       enable: false
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus

max_0.025:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus


# min_0.05:
#   solving:
#     mga:
#       enable: true
#       sense: min
#       slack: 0.05
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

# max_0.05:
#   solving:
#     mga:
#       enable: true
#       sense: max
#       slack: 0.05
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

# min_0.1:
#   solving:
#     mga:
#       enable: true
#       sense: min
#       slack: 0.1
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

# max_0.1:
#   solving:
#     mga:
#       enable: true
#       sense: max
#       slack: 0.1
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

# min_0.15:
#   solving:
#     mga:
#       enable: true
#       sense: min
#       slack: 0.15
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

# max_0.15:
#   solving:
#     mga:
#       enable: true
#       sense: max
#       slack: 0.15
#     solver:
#       name: gurobi
#       options: gurobi-numeric-focus

######## 710 scenarios carbon costs ########
710_optimal:
  solving:
    mga:
      enable: false
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.025:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.025:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.05:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.05:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.1:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.1:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_min_0.15:
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710

710_max_0.15:
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15
    solver:
      name: gurobi
      options: gurobi-numeric-focus
  sector:
    co2_sequestration_potential:
      2050: 710


####### default scenarios #######
default_optimal:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false

default_min_0.025:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus


default_max_0.025:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_min_0.05:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_max_0.05:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_min_0.1:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_max_0.1:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_min_0.15:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_max_0.15:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15
    solver:
      name: gurobi
      options: gurobi-numeric-focus

######## 710 scenarios default ########  

default_710_optimal:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710


default_710_min_0.025:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_min_0.05:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.05
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_max_0.025:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.025
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_max_0.05:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.05
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_min_0.1:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.1
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_max_0.1:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.1
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_min_0.15:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: min
      slack: 0.15
    solver:
      name: gurobi
      options: gurobi-numeric-focus

default_710_max_0.15:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0
  sector:
    renewable_emissions:
      enable: false
    co2_sequestration_potential:
      2050: 710
  solving:
    mga:
      enable: true
      sense: max
      slack: 0.15
    solver:
      name: gurobi
      options: gurobi-numeric-focus