# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

# normal:
#   electricity:
#     renewable_carriers:
#     - solar
#     - onwind
#     - offwind-ac
#     - offwind-dc
#     - hydro

no_biomass_emissions:
  biomass:
    emission_factors:
      agricultural waste: 0
      fuelwood residues: 0
      secondary forestry residues: 0
      sawdust: 0
      residues from landscape care: 0
      grasses: 0
      woody crops: 0
      fuelwoodRW: 0
      manure: 0
      sludge: 0
      C&P_RW: 0

biomass_emissions:
  biomass:
    emission_factors: #same as default
      agricultural waste: 0.03528 # 9.8
      fuelwood residues: 0.1476 #41
      secondary forestry residues: 0.396 #110
      sawdust: 0.396 #110
      residues from landscape care: 0
      grasses: 0.216
      woody crops: 0.18
      fuelwoodRW: 0.2844 #79
      manure: 0.04932 #13.7
      sludge: 0
      C&P_RW: 0.414 #115
      