# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers


low_price_no_em:
  stochasticity: #gas price used in the standard model:  24.568 EUR/MWh_th
    gas_price:
      enable: true
      distribution: scenarios #options: scenarios, normal, uniform
      scenarios: #add as many scenarios as you want, first the value of the gas price in  EUR/MWh_th, then the probability of that scenario 
        - 20, 1

high_price_no_em:
  stochasticity: #gas price used in the standard model:  24.568 EUR/MWh_th
    gas_price:
      enable: true
      distribution: scenarios #options: scenarios, normal, uniform
      scenarios: #add as many scenarios as you want, first the value of the gas price in  EUR/MWh_th, then the probability of that scenario 
        - 40, 1

low_price_em:
  stochasticity: #gas price used in the standard model:  24.568 EUR/MWh_th
    gas_price:
      enable: true
      distribution: scenarios #options: scenarios, normal, uniform
      scenarios: #add as many scenarios as you want, first the value of the gas price in  EUR/MWh_th, then the probability of that scenario 
        - 20, 1
  biomass:
    emission_factors:
      forest residues biomass: 0.1 # tCO2/MWh 0.1
      rest product biomass: 0.02 # tCO2//MWh 0.02
      biogas: 0 # tCO2/MWh

high_price_em:
  stochasticity: #gas price used in the standard model:  24.568 EUR/MWh_th
    gas_price:
      enable: true
      distribution: scenarios #options: scenarios, normal, uniform
      scenarios: #add as many scenarios as you want, first the value of the gas price in  EUR/MWh_th, then the probability of that scenario 
        - 40, 1
  biomass:
    emission_factors:
      forest residues biomass: 0.1 # tCO2/MWh 0.1
      rest product biomass: 0.02 # tCO2//MWh 0.02
      biogas: 0 # tCO2/MWh

low_price_high_em:
  stochasticity: #gas price used in the standard model:  24.568 EUR/MWh_th
    gas_price:
      enable: true
      distribution: scenarios #options: scenarios, normal, uniform
      scenarios: #add as many scenarios as you want, first the value of the gas price in  EUR/MWh_th, then the probability of that scenario 
        - 20, 1
  biomass:
    emission_factors:
      forest residues biomass: 0.2 # tCO2/MWh 0.2
      rest product biomass: 0.04 # tCO2//MWh 0.04
      biogas: 0 # tCO2/MWh

high_price_high_em:
  stochasticity: #gas price used in the standard model:  24.568 EUR/MWh_th
    gas_price:
      enable: true
      distribution: scenarios #options: scenarios, normal, uniform
      scenarios: #add as many scenarios as you want, first the value of the gas price in  EUR/MWh_th, then the probability of that scenario 
        - 40, 1
  biomass:
    emission_factors:
      forest residues biomass: 0.2 # tCO2/MWh 0.2
      rest product biomass: 0.04 # tCO2//MWh 0.04
      biogas: 0 # tCO2/MWh